# Generated by Django 5.2.7 on 2025-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabletales', '0003_recipe_description_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipes/default.png', null=True, upload_to='recipes/'),
        ),
    ]
